get all nunpy methods,usefulness and give 1 example for each


In [ ]:
methods of nunpy are
#Arrays in  Numpy
#uses of array in numpy
1. it is a table of element(usually numbers)all of the same type,indexed by a tuple of positive integers
2. in numpy dimensions are called axes,the no of axes is rank
3. numpy's array class is called ndarray.it is also known by the alias array
#example

In [2]:
import numpy as np


In [3]:
my_array=np.array([[1,2,3],[4,2,5]])
type(my_array)

numpy.ndarray

In [4]:
my_array.ndim

2

In [5]:
my_array.shape

(2, 3)

In [6]:
my_array.size

6

In [7]:
my_array.dtype

dtype('int32')

In [ ]:
2.# Array creation
#uses:. array can be created from a regular python list or tuple using the array function.
   #the type of the resulting array is deduced from the type of the elements in the sequence,element of an array are originally unknown, but its size is known
   #for example:np.zeros,np.ones,np.full,np.empty etc
    

In [8]:
import numpy as np

In [9]:
a=np.array([[1,2,4],[5,8,7]])#creating array from the list with float type
a

array([[1, 2, 4],
       [5, 8, 7]])

In [10]:
b=np.array((a))#creating array from tupple
b

array([[1, 2, 4],
       [5, 8, 7]])

In [12]:
d=np.full((3,3),6)#creating a constant value array of complex type
d

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [23]:
e=np.random.random((2,2))#creating anarray with random values
e

array([[0.96519618, 0.05101577],
       [0.46190919, 0.23016857]])

In [37]:
e.shape

(2, 2)

In [25]:
e.dtype

dtype('float64')

In [26]:
e.ndim

2

In [11]:
f=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
f

array([[1, 2, 3, 4],
       [5, 2, 4, 2],
       [1, 2, 0, 1]])

In [12]:
f.shape

(3, 4)

In [28]:
newf=f.reshape(2,2,3)#reshape into 2,2rows,3column
newf

array([[[1, 2, 3],
        [4, 5, 2]],

       [[4, 2, 1],
        [2, 0, 1]]])

In [35]:
w=newf.flatten()
w

array([1, 2, 3, 4, 5, 2, 4, 2, 1, 2, 0, 1])

In [28]:
newf1=a.reshape(2,1,3)#reshape into 2,1row,3column
newf1

array([[[1, 2, 4]],

       [[5, 8, 7]]])

In [30]:
arr=np.array((a))
arr

array([[1, 2, 4],
       [5, 8, 7]])

In [31]:
flarr=arr.flatten()
flarr

array([1, 2, 4, 5, 8, 7])

In [32]:
flat=f.flatten()
flat

array([1, 2, 3, 4, 5, 2, 4, 2, 1, 2, 0, 1])

In [ ]:
#3.Array indexing:it is important for analysing and manipulating the array object
 #array indexing can be use in my ways
#slicing,integer array indexing,boolean array indexing

In [33]:
g=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2]])
g

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [34]:
slice=g[:2,::2]
slice

array([[-1.,  0.],
       [ 4.,  6.]])

In [1]:
#Basic operations:arithmetic operators can be used to do element wise operation
#in case of =+,-=,*= operators, the existing array is modified