In [ ]:
#### my name is adejoke

#### studied statistics

In [1]:
1<2#boolean statement(true/false)

True

In [3]:
a=1
b=2
a>b


False

In [6]:
a=2#sum of two variables
b=2
c=4
c=a+b
c

4

In [7]:
d=5#boolean statement
e=6
e>d


True

In [10]:
x=10#assigning value to a variable
x

10

In [12]:
x-2#subtraction of two variables


8

In [15]:
x**5#exponentiation of a variable

100000

In [16]:
x+5

15

In [17]:
x-5

5

In [18]:
x*5#multiplication of two variables

50

In [19]:
x/5#division of two variables

2.0

In [20]:
x%5#remainder of a variable

0

In [21]:
x%8

2

In [22]:
str((1,2,3))

'(1, 2, 3)'

In [23]:
bool((True,False))

True

In [25]:
type(True)

bool

In [28]:
a=bool(('True','False'))

In [30]:
type(a)

bool

In [34]:
#help(float)

In [38]:
my_string='learning'
my_string+'reading'
print('I love are:', my_string+ ' ' 'and' + ' ' + ' '+'reading')


I love learning and  reading


In [43]:
my_name='adejoke'
my_state_of_origin='osun'
print('my details are:','my name is', my_name + ' '+ 'and', 'my state of origin is', my_state_of_origin )

my details are: my name is adejoke and my state of origin is osun


In [44]:
i_studied='statistics'
my_school='OAU'
print('my details are:','I studied',i_studied + ' '+ 'and', 'My school is', my_school)

my details are: I studied statistics and My school is OAU


In [46]:
 i_studied + 'my course'

'statisticsmy course'

In [49]:
print('my course is', i_studied  )

my course is statistics


In [52]:
print('My course is', i_studied +' '+ 'and', 'am in a department in', my_school)

My course is statistics and am in a department in OAU


In [59]:
local_govt='daura'
state='katsina town'
print('i served in', state +' '+ 'in', local_govt)


i served in katsina town in daura


In [61]:
local_govt + ' '+ state

'daura katsina town'

In [6]:
a='is'
b='fine'
my_name=['my','name',a,b]#i.e index starts at 0from the left my=0,name=1,a=2 and b=3 but from the right it starts from -1
my_name

['my', 'name', 'is', 'fine']

In [15]:
my_othername=[['joke','bimpe','lola'],['joy','tayo','funmi'],['sayo','bayo','ojo']]#list of list
my_othername

[['joke', 'bimpe', 'lola'], ['joy', 'tayo', 'funmi'], ['sayo', 'bayo', 'ojo']]

In [9]:
my_name[1]

'name'

In [10]:
my_name[-1]

'fine'

In [11]:
my_name[3]

'fine'

In [12]:
my_name[-3]

'name'

In [13]:
my_othername[0]#subset of list of list since index statr from 0,it wud bring out the first list

['joke', 'bimpe', 'lola']

In [17]:
my_othername[0][0]#subset0f subset of list of list

'joke'

In [114]:
my_othername[1]

['joy', 'tayo', 'funmi']

In [115]:
my_othername[1][1]

'tayo'

In [116]:
my_othername[2]

['sayo', 'bayo', 'ojo']

In [117]:
my_othername[2][2]

'ojo'

In [118]:
my_othername[2][-2]

'bayo'

In [119]:
print('my other names are:',my_othername)

my other names are: [['joke', 'bimpe', 'lola'], ['joy', 'tayo', 'funmi'], ['sayo', 'bayo', 'ojo']]


In [120]:
my_name[1:4]#slicing i.e since indexing starts from 0 then 1:4 wud be from 1 to 3,then 4 will be excluded

['name', 'is', 'fine']

In [121]:
my_name[1:]#it means select items after index 0

['name', 'is', 'fine']

In [122]:
my_name[:3]#it means select items b4 3

['my', 'name', 'is']

In [123]:
my_name[:2]#it means select items bfor 2

['my', 'name']

In [124]:
my_othername[:1]#slicing i.e it means select items b

[['joke', 'bimpe', 'lola']]

In [125]:
my_othername[:]

[['joke', 'bimpe', 'lola'], ['joy', 'tayo', 'funmi'], ['sayo', 'bayo', 'ojo']]

In [126]:
new_list=[1,2,6,3,4,8,9,5,6,9,7,8,9,10]#method(note):index start from 0i.e1=0,2=1...
new_list.index(8)

5

In [127]:
new_list.count(9)

3

In [128]:
new_list.append(11)#means it will include the 11:it does not that two values at a time,it takes it as a list.

In [129]:
new_list

[1, 2, 6, 3, 4, 8, 9, 5, 6, 9, 7, 8, 9, 10, 11]

In [130]:
#new_list.append([12,13])#append wud make it looks like list of listi.e[[12,13]]

In [131]:
new_list

[1, 2, 6, 3, 4, 8, 9, 5, 6, 9, 7, 8, 9, 10, 11]

In [132]:
new_list.extend([12,13])#extend wud make it looks seperately
new_list

[1, 2, 6, 3, 4, 8, 9, 5, 6, 9, 7, 8, 9, 10, 11, 12, 13]

In [133]:
del(new_list[0:5])#u cant from 1 starting from 0 to 4,it means the 5th one wont be included

In [134]:
new_list

[8, 9, 5, 6, 9, 7, 8, 9, 10, 11, 12, 13]

In [135]:
new_list.pop(-1)

13

In [136]:
new_list

[8, 9, 5, 6, 9, 7, 8, 9, 10, 11, 12]

In [137]:
new_list.pop(10)#counting 10 starting from 0 then 12 will be removed

12

In [138]:
new_list

[8, 9, 5, 6, 9, 7, 8, 9, 10, 11]

In [139]:
new_list.sort()#it will be in ascending order
new_list

[5, 6, 7, 8, 8, 9, 9, 9, 10, 11]

In [140]:
new_list.insert(0,15)#if i want it to give me suggestion will just click on shift tab...the option wud show

In [141]:
new_list

[15, 5, 6, 7, 8, 8, 9, 9, 9, 10, 11]

In [142]:
new_list.insert(4,8)

In [143]:
new_list

[15, 5, 6, 7, 8, 8, 8, 9, 9, 9, 10, 11]

In [145]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [ ]:
#nunpy means numerical python,they are use for algebraic operation and are used for writting formulars,

In [147]:
import numpy as np

In [148]:
new_list

[15, 5, 6, 7, 8, 8, 8, 9, 9, 9, 10, 11]

In [149]:
new_list_array=np.array(new_list)#the number of items is always the number of rows.(note).:array turns values into matrix
new_list_array

array([15,  5,  6,  7,  8,  8,  8,  9,  9,  9, 10, 11])

In [153]:
my_array=np.array([[1,2,3,4,5],[10,11,12,13,14],[8,2,4,2,8]])
my_array

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14],
       [ 8,  2,  4,  2,  8]])

In [154]:
my_array.shape#it means we are having 3rows,5 coloums

(3, 5)

In [155]:
new_list_array.shape#it means we are having 12 rows,1 column

(12,)

In [156]:
my_array[:,0]#picking all rows but the first column

array([ 1, 10,  8])

In [157]:
my_array[:,4]#picking all rows but the 4th column usind index0

array([ 5, 14,  8])

In [163]:
my_array[1:2, 1]#it means picking row index1 but wont reach 2 but column1 which will be index0

array([11])

In [160]:
my_array[:4]#since there is no (,) it means we are only specific on the rows so it means we are picking to 3

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14],
       [ 8,  2,  4,  2,  8]])

In [164]:
my_array[0:2,2]

array([ 3, 12])

In [165]:
np.mean(my_array)

6.6

In [166]:
np.median(my_array)

5.0

In [167]:
my_array[0:2,4]#it starts from index 0 and 1 but column 4

array([ 5, 14])

In [168]:
my_array[1:2,4]

array([14])

In [169]:
my_array[0:1,1]

array([2])

In [170]:
classwork_array=np.array([[2,4,6,8],[9,3,8,7],[2,5,9,8],[1,6,2,3]])
classwork_array

array([[2, 4, 6, 8],
       [9, 3, 8, 7],
       [2, 5, 9, 8],
       [1, 6, 2, 3]])

In [172]:
classwork_array[1:3,2]

array([8, 9])

In [174]:
classwork_array[2:4,1:3]

array([[5, 9],
       [6, 2]])

In [175]:
classwork_array[:,2]

array([6, 8, 9, 2])

In [ ]:
#get all nunpy methods,usefulness and give 1 example for each
